# Numpy
NumPy stands for Numerical Python. NumPy is the fundamental package for scientific computing in Python. It is an open source Python library that is used for working with multidimensional array objects.
##Installing Numpy
```
!pip install numpy
 ```
##Importing Numpy in Python Notebook
```
import numpy as np
```


In [ ]:
!pip install numpy

In [ ]:
import numpy as np

##Coverting a List to Array
```
np.array(object, dtype=None, ndmin=0)
```
**object =**  (Required) The input data (list, tuple, nested list, etc.)  
**dtype =**	 (Optional) Data type you want the array to be (e.g., int32, float64, etc.)  
**ndmin =**   (Optional) It forces the array to have at least the given number of dimensions. Default=0, i.e Don't force any extra dimensions.

In [ ]:
# 1) Converting an list to array using variable
lst = [1,2,3,4]
print(lst)
print(type(lst))

arr = np.array(lst)
print(type(arr))
print(arr)

[1, 2, 3, 4]
<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4]


In [ ]:
#2) Converting an list to array with dtype
arr=np.array([1, 2, 3],dtype=float)
print("array is of type: ",type(arr))
print("But type of each data is: ",type(arr[1]))

array is of type:  <class 'numpy.ndarray'>
But type of each data is:  <class 'numpy.float64'>


In [ ]:
# 3) Converting an list to array with ndmin
arr=np.array([1, 2, 3], ndmin=2)
print(arr)
print("Dimention of this array is: ",arr.ndim)

[[1 2 3]]
Dimention of this array is:  2


In [ ]:
#4) Multidimensional array
lst=[[1,2,3],[4,5,6]]
print("Elements of list are")
print(lst)
arr=np.array(lst)
print("Respective multidimensional array is")
print(arr)

Elements of list are
[[1, 2, 3], [4, 5, 6]]
Respective multidimensional array is
[[1 2 3]
 [4 5 6]]


# **Functions to create array**
1. **Arrange:** It creates an array by using the evenly spaced values(step) over the given interval(start,stop).
2. **Zeros Function:** The zeros function returns a new array of given shape and type, <U> with zeros. </U>  
3. **ones Functions:** The ones function returns a new array of given shape and type, <U> with ones. </U>
4. **Size:** This function return the number of elements along a given axis (0 - Rows | 1 - Columns) or with in the complete array.
5. **Shape:** The shape of an array can be defined as the number of elements in each dimension.


## **Arrange Function**  
**Arange:** It creates an array by using the evenly spaced values(step) over the given interval(start,stop).
```
np.arange(start, stop, step, dtype)
```
start: The starting of an interval. (default = 0)  
stop: represents the value at which the interval ends excluding this value.  
step: The number by which the interval values change.  
dtype: the data type of the numpy array items. (Default = int64)
> Example:
>```
>arr = np.arange(1,10,2)
>```

In [ ]:
#arrange function
arr = np.arange(1,10,2)
print(arr)
print(type(arr[1]))

[1 3 5 7 9]
<class 'numpy.int64'>


In [ ]:
arr=np.arange(1,10,dtype=float)
print(arr)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


## **Zeros and Ones**
1. **Zeros Function:** The zeros function returns a new array of given shape and type, <U> with zeros. </U>  
2. **ones Functions:** The ones function returns a new array of given shape and type, <U> with ones. </U>
```
np.zeros(shape = (), dtype = None order=' ')
np.ones(shape = (), dtype = None, order=' ')
```
shape: (Required) Tuple specifying array dimensions (e.g., (3, 4))  
dtype: (Optional) Data type of array elements (default: float64)  
order: (Optional) Memory layout ('C' for row-major, 'F' for column-major)  
>Example
>```
>arr=np.zeros((2,3) , dtype = float)
>arr=np.ones((2,3) , dtype = int)
>```


In [ ]:
#creating zeros matrix
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Creating ones matrix
ones=np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Creating Zeros matrix with dtype int
zeros=np.zeros((2,3),dtype=int)
print(zeros)

[[0 0 0]
 [0 0 0]]


In [ ]:
# Creating ones matrix with dtype int
ones=np.ones((2,3),dtype=int)
print(ones)

[[1 1 1]
 [1 1 1]]


In [ ]:
# Creating the 3d Zeros matriz
zeros_3d=np.zeros((3,4,5),dtype=int)
print(zeros_3d)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


## Empty
**Empty:** Return am empty array of given shape and type
```
np.empty(shape, dtype=float)
```
shape:	Shape of the array (as a tuple or int)  
dtype:	Data type of the output array (default = float)

---
#### Note
- When you're going to fill the array immediately using loops or other logic  
- Faster than zeros() or ones() (because it skips initialization)
---

In [ ]:
a=np.empty(4)
print(a)

[4.9e-324 9.9e-324 1.5e-323 2.0e-323]


In [ ]:
a=np.empty((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


## Eye Function
**eye:** np.eye() creates a 2D identity matrix — a square or rectangular matrix where all the values on the main diagonal are 1 and all others are 0.  
```
np.eye(N, M=None, k=0, dtype=float)
```
N: It is use to specify <U> number of rows </U> (Required)  
M: It is use to specify <U> Number of columns </U> (default = N)  
dtype: Data type of the output (default = float)  
k: Index of the diagonal (default = 0 → main diagonal) (Optional)
-   k= 0: Main diagonal  
-   k> 0: Diagonal above the main
-   k< 0: Diagonal below the main
---
#### Note
- Use k to shift diagonal up/down  
- Default is square with main diagonal (k=0)

In [ ]:
# Creating square martix of diagonal 1
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Creating rectangular matrix of diagonal 1
np.eye(4, 6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [ ]:
#Creating the matrix using dtype attribute
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
# Shifting the Diagonal in rectangular Matrix
print("K = 1")
print(np.eye(4,6,k = 1, dtype = int))
print("K = 0")
print(np.eye(4,6,k = 0, dtype = int))
print("K = -1")
print(np.eye(4,6,k = -1, dtype = int))

K = 1
[[0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]
K = 0
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]]
K = -1
[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]]


In [ ]:
# Shifting the Diagonal in square Matrix
print("K = 1")
print(np.eye(5,k = 1, dtype = int))
print("K = 0")
print(np.eye(5,k = 0, dtype = int))
print("K = -1")
print(np.eye(5,k = -1, dtype = int))

K = 1
[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]
K = 0
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
K = -1
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


##Random
**Random:** `np.random` is a module in NumPy that provides functions to generate random numbers of different types, shapes, and distributions.  
It can create:
- Random floats (random, rand, randn, etc.)
- Random integers (randint)
- Random values from normal or custom distributions
- Random selections (choice, shuffle, permutation)
- And supports reproducibility with seed


### a) Random.random
**random.random / random.rand :** It is used to generate random float numbers in the range [0.0, 1.0), i.e., it includes 0.0 but excludes 1.0.
```
np.random.random(size=None)
np.random.rand(d0, d1, ..., dn)
```
`np.random.random()` : It contain only one prameter i.e. tupple of required size(Shape in form of tuple as arguments)  
`np.random.rand(d0, d1, ..., dn)` : It contain the various positional arguments(Shape as separate arguments)

In [ ]:
# 1D Array of size 5
arr1 = np.random.random(5)     # Using tuple/int
arr2 = np.random.rand(5)       # Using positional argument
print(arr1)
print(arr2)

[0.12341382 0.3999138  0.64172032 0.79978841 0.34124064]
[0.84798128 0.12446348 0.61907459 0.05975359 0.26481077]


In [ ]:
# 2D Array of size (2,3)
arr_2D_1 = np.random.random((2, 3))   # Tuple passed in
arr_2D_2 = np.random.rand(2, 3)       # Shape as separate arguments
print("2D array of size (2,3): \n",arr_2D_1)
print("2D array of size (2,3): \n",arr_2D_2)

2D array of size (2,3): 
 [[0.51754329 0.97279617 0.25081374]
 [0.0631058  0.55231124 0.58348589]]
2D array of size (2,3): 
 [[0.4472626  0.68969052 0.97556556]
 [0.78596977 0.29778256 0.59192283]]


In [ ]:
# 3D Array of size (2,2,2)
arr_3D_1 = np.random.random((2, 2, 2))
arr_3D_2 = np.random.rand(2, 2, 2)
print("3D array of size (2,2,2): \n",arr_3D_1,"\n\n\n")
print("3D array of size (2,2,2): \n",arr_3D_2)

3D array of size (2,2,2): 
 [[[0.3721192  0.21859596]
  [0.72719486 0.8836644 ]]

 [[0.5344948  0.81808731]
  [0.87454646 0.14076996]]] 



3D array of size (2,2,2): 
 [[[0.52461911 0.94662811]
  [0.93755932 0.14142853]]

 [[0.55611342 0.38225731]
  [0.9325482  0.80427658]]]


### b) np.random.randint
generates random integers from the values greater than or equal to `low` and less than `high` (i.e., [low, high)).

```
np.random.randint(low, high=None, size=None, dtype=int, endpoint=False)
```
Low → (required) Lower bound of the range (included)
high → (optional)  Upper bound of the range (default = excluded). If not provided, range is [0, low)  
size → (optional) Shape of the output array (default = None); if not provided, returns a single scalar integer instead of an array.  
dtype → (optional) Data type of output values (default = int). Always int only  
endpoint → (optional) Whether to include the high value in output (default = False)  

In [ ]:
# Generating array using low only
np.random.randint(5, size=3) # behaves like range [0, low)

array([1, 3, 4])

In [ ]:
# Generating array using high only without giving size
np.random.randint(10, 20) # Return only single scaler integer insted of array

15

In [ ]:
# Generating 1D array using size
np.random.randint(1, 100, size=5)

array([82, 37,  2, 56, 33])

In [ ]:
# Generating 2D array using size
np.random.randint(1, 100, size=(2, 3))

array([[44, 18, 83],
       [55, 85, 52]])

In [ ]:
np.random.randint(100, 200, size=(2, 2))

array([[148, 175],
       [119, 129]])

### c) np.random.randn
The `numpy.random.randn()` function creates an array of specified shape and fills it with random values as per standard normal distribution.
```
np.random.randn(d0, d1, d2, ..., dn)
```
d0, d1, ..., dn: It contain the various positional arguments(Shape as separate arguments)



In [ ]:
np.random.randn()
# Output = one random float from standard normal distribution

-0.17605156341029857

In [ ]:
#1D array with 5 elements
np.random.randn(5)

array([-0.53922362, -0.28377252, -0.21551731, -0.05534054, -0.19469622])

In [ ]:
# 2D array (2 rows, 3 columns)
np.random.randn(2, 3)

array([[-2.16473803, -0.87742818, -1.04308364],
       [ 0.70528542,  1.08846462, -1.001114  ]])

In [ ]:
# 3D array (2 × 2 × 2)
np.random.randn(2, 2, 2)

array([[[-0.82664801,  1.21007681],
        [-0.12153015,  0.28546881]],

       [[ 0.5733979 ,  0.80956511],
        [ 0.60914194, -0.10794896]]])

# Numpy attriute

## **Size**
**Size:**  This function return the number of elements along a given axis (0 - Rows | 1 - Columns) or with in the complete array.
```
np.size(arr, axis=None)
```
axis:  (Optional) It represent along which the elements (rows or columns) are counted.


In [ ]:
#Size function with 2d array
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
print(arr,"\n")
print('Total : ', arr.size)# without Axis as attributes (total)
print('Total : ', np.size(arr))# without Axis with function (total)
print('Rows  : ', np.size(arr,0)) # With axis
print('Cols  : ', np.size(arr,1)) # With axis

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]] 

Total :  12
Total :  12
Rows  :  4
Cols  :  3


In [ ]:
#Size function with 3D array
Arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(Arr3d,"\n")
print('Total : ', np.size(Arr3d))# without Axis
print('Rows  : ', np.size(Arr3d,0)) # With axis
print('Cols  : ', np.size(Arr3d,1)) # With axis
print('Depth : ', np.size(Arr3d,2)) # With axis

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]] 

Total :  18
Rows  :  2
Cols  :  3
Depth :  3


## **Shape**
**Shape:** The shape of an array can be defined as the number of elements in each dimension. Dimension is the number of indices or subscripts, that we require in order to specify an individual element of an array.
```
arr.shape      # Act as an attribute
np.shape(arr)  # Act as an function and array is its argument
```

In [ ]:
# Getting the shape of an 1d-array
arr=np.array([1,2,3,4])
print(arr)
print(arr.shape)
print(np.shape(arr))

[1 2 3 4]
(4,)
(4,)


In [ ]:
#Getting shape of matrix
arr=np.zeros((2,3),dtype=int)
print(arr)
print(arr.shape)
print(np.shape(arr))

[[0 0 0]
 [0 0 0]]
(2, 3)
(2, 3)


## Dtype
**dtype:** dtype stands for "data type". It defines the type of elements stored in a NumPy array
— e.g., int, float, bool, string, etc.
```
arr.dtype
```

In [ ]:
arr = np.arange(4)
print(arr.dtype)
arr.dtype

int64


dtype('int64')

## ndim
This function return the number of dimensions of an array.
```
arr.ndim
np.ndim()
```
####Return the value as:
- 1D → single row of values
- 2D → rows & columns (like a matrix)
- 3D → depth, rows, columns (like image stack)
- and so on...

In [ ]:
print(arr)
print("Print ndim of the array using attribute: ",arr.ndim)
print("Print ndim of the array using function: ",np.ndim(arr))

[0 1 2 3]
Print ndim of the array using attribute:  1
Print ndim of the array using function:  1


# Reshape function